# Setup
title:               Neuralife
tagline:             Hashir Ahmad
description:         'Welcome to my blog! I hope you find something interesting here.'
url:                 https://hash-ir.github.io
baseurl:             ''
paginate:            5
permalink:           pretty
avatar:              https://drive.google.com/file/d/1b06yR4N3QlM7iX_OBNHlBmLsDiYMqIfv/view?usp=sharing

# About/contact
author:
  name:              Hashir 
  url:               https://github.com/hash-ir
  email:             hashirahmad@zhcet.ac.in

# Gems
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Custom vars
version:             1.1.0
google_analytics_id: UA-171868650-1

